// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyakemndgixcawahjdxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5YWtlbW5kZ2l4Y2F3YWhqZHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTcwMTAsImV4cCI6MjA2OTQzMzAxMH0.mrxfjLtFJJfcPK_mw08LH8JTfVSq5yXr5-KARoiKr5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});